# Generated by Django 2.1.1 on 2018-12-05 22:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCmic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=2000, verbose_name='企业简介')),
            ],
            options={
                'verbose_name': '企业简介',
                'verbose_name_plural': '企业简介',
            },
        ),
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel', models.IntegerField(default=5, verbose_name='轮播时间间隔')),
                ('media_id', models.CharField(max_length=50, verbose_name='图片/视频编码')),
                ('media_info', models.CharField(max_length=100, verbose_name='图片视频/描述')),
                ('sort_order', models.IntegerField(verbose_name='图片/视频排序')),
                ('image', models.ImageField(upload_to='Advertise_img', verbose_name='图片')),
                ('fill_color', models.CharField(blank=True, max_length=10, null=True, verbose_name='图片填充色')),
                ('link_addr', models.CharField(blank=True, max_length=300, null=True, verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '轮播图片配置',
                'verbose_name_plural': '轮播图片配置',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文化标题')),
                ('content', models.CharField(max_length=100, verbose_name='文化描述')),
                ('sortorder', models.IntegerField(verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '企业文化',
                'verbose_name_plural': '企业文化',
            },
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_id', models.CharField(max_length=50, verbose_name='字典编码')),
                ('dict_name', models.CharField(max_length=50, verbose_name='字典名称')),
                ('group_id', models.CharField(max_length=50, verbose_name='字典组编码')),
                ('group_name', models.CharField(max_length=50, verbose_name='字典组名称')),
            ],
            options={
                'verbose_name': '字典配置',
                'verbose_name_plural': '字典配置',
            },
        ),
        migrations.CreateModel(
            name='FrendlyLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='链接名称')),
                ('address', models.URLField(verbose_name='链接地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorname', models.CharField(max_length=100, verbose_name='荣誉名称')),
                ('honorimage', models.ImageField(upload_to='honor', verbose_name='荣誉照片')),
                ('sortorder', models.IntegerField(verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '品牌荣誉',
                'verbose_name_plural': '品牌荣誉',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Logo图标')),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=50, verbose_name='菜单编码')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('sort_order', models.IntegerField(verbose_name='菜单排序')),
                ('link', models.CharField(blank=True, max_length=50, null=True, verbose_name='跳转地址')),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_parentid', to='officalweb.Menus', verbose_name='上级菜单')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus_status', to='officalweb.DictItem', verbose_name='菜单状态')),
            ],
            options={
                'verbose_name': '菜单配置',
                'verbose_name_plural': '菜单配置',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='产品图片')),
                ('image_desc', models.CharField(max_length=200, verbose_name='图片描述')),
            ],
            options={
                'verbose_name': '产品详情',
                'verbose_name_plural': '产品详情',
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_desc', models.CharField(max_length=500, verbose_name='产品描述')),
                ('product_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='规格')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('product_unit', models.CharField(blank=True, max_length=5, null=True, verbose_name='计价方式')),
                ('product_type', models.CharField(max_length=20, verbose_name='产品类别（如：新品、常规)')),
                ('image_url', models.ImageField(upload_to='product_img', verbose_name='图片/视频')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productList_status', to='officalweb.DictItem', verbose_name='产品状态')),
            ],
            options={
                'verbose_name': '产品配置',
                'verbose_name_plural': '产品配置',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=20, verbose_name='产品分类编码')),
                ('typename', models.CharField(max_length=50, verbose_name='产品分类名称')),
                ('image', models.ImageField(upload_to='prodtype', verbose_name='分类图片')),
                ('order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.AddField(
            model_name='productlist',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officalweb.ProductType', verbose_name='产品编码'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officalweb.ProductList', verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertise_media_type', to='officalweb.DictItem', verbose_name='媒体分类'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertise_page', to='officalweb.Menus', verbose_name='关联页面'),
        ),
        migrations.AddField(
            model_name='advertise',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertise_status', to='officalweb.DictItem', verbose_name='媒体状态'),
        ),
    ]
