# Generated by Django 2.1.1 on 2018-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officalweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='小图标')),
                ('content', models.CharField(max_length=50, verbose_name='项目值')),
                ('sortorder', models.IntegerField(verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
            },
        ),
    ]
